#ifndef PROXYTASK_H
#define PROXYTASK_H

#include <QThread>
#include <QObject>
#include <QTcpSocket>
#include <QTcpServer>

#include "common.h"

// Q_OBJECT missing in the original file generated by class wizard.
// because we set this class with base class QRunnable
// with no inheritance in the class wizard
// We do not have this. So, we cannot use signal/slot
// But we need them.
// Thus, we should use multiple inheritance: QObject inserted here

class HTTPThread : public QThread
{
    Q_OBJECT
public:
    HTTPThread(int socketDescriptor, QObject *parent);

    void run() Q_DECL_OVERRIDE;

signals:
    void error(QTcpSocket::SocketError socketError);

public slots:
    void ClientBytesWritten(qint64 bytes);
    void ClientReadyRead();

    void DownstreamConnected();
    void DownstreamReadyRead();

private:
    QTcpSocket ClientSocket;
    QTcpSocket DownstreamSocket;

private:
    int socketDescriptor;

    std::string dataRead = "";
    std::string recvHost = "";
    std::string domain = "";

    std::string DestinationStr;
    std::vector<std::string>* destinationIPPort;
    unsigned short Port;

};

#endif // PROXYTASK_H
