#ifndef PROXYTASK_H
#define PROXYTASK_H

#include <QThread>
#include <QObject>
#include <QTcpSocket>
#include <QTcpServer>

#include "common.h"
#include "routeinfo.h"

// Q_OBJECT missing in the original file generated by class wizard.
// because we set this class with base class QRunnable
// with no inheritance in the class wizard
// We do not have this. So, we cannot use signal/slot
// But we need them.
// Thus, we should use multiple inheritance: QObject inserted here

class HTTPClient : public QObject
{
    Q_OBJECT
public:
    HTTPClient(int socketDescriptor);

    void run();

signals:
    void error(QTcpSocket::SocketError socketError);

public slots:
    void ClientReadyRead();
    void ClientDisconnected();

    void DownstreamConnected();
    void DownstreamReadyRead();
    void DownstreamDisconnected();

private:
    QTcpSocket* ClientSocket;
    QTcpSocket* DownstreamSocket;

private:
    int socketDescriptor;

    std::string dataRead = "";
    std::string recvHost = "";
    std::string domain = "";

    RouteInfo Destination;

    qint64 DownstreamBytesRead = 0;

};

#endif // PROXYTASK_H
